-- 코드를 입력하세요




SELECT  RI.REST_ID, REST_NAME, FOOD_TYPE,FAVORITES,ADDRESS ,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO RI, REST_REVIEW RV
WHERE RI.REST_ID=RV.REST_ID AND ADDRESS LIKE ('서울%')
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;

