-- 코드를 입력하세요
SELECT USB.TITLE, USB.BOARD_ID,UGR.REPLY_ID, UGR.WRITER_ID,UGR.CONTENTS,DATE_FORMAT(UGR.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD USB 
INNER JOIN USED_GOODS_REPLY UGR ON USB.BOARD_ID = UGR.BOARD_ID
WHERE USB.CREATED_DATE LIKE '2022-10-__'
ORDER BY UGR.CREATED_DATE ASC, USB.TITLE ASC;
